# optimum-cli export onnx   --model  phuong-tk-nguyen/resnet-50-finetuned-cifar10 --task image-classification ./cifar10
encoderfile:
  name: test-img-class
  path: models/image_classification
  model_type: image_classification
  output_path: ./test-img-class.encoderfile
  base_binary_path: ./target/debug/encoderfile-runtime
  no_download: true
