const BUILD_VARS: &[&str] = &[
    "MODEL_WEIGHTS_PATH",
    "TOKENIZER_PATH",
    "MODEL_CONFIG_PATH",
    "MODEL_TYPE",
    "MODEL_NAME",
];

const TRANSFORM_FILE: &'static str = r##"
// Generated by Encoderfile

#[allow(dead_code)]
const TRANSFORM: Option<&'static str> = Some(include_str!(env!("TRANSFORM_PATH")));
"##;

const TRANSFORM_FILE_NONE: &'static str = r##"
// Generated by Encoderfile

#[allow(dead_code)]
const TRANSFORM: Option<&'static str> = None;
"##;

fn main() -> Result<(), Box<dyn std::error::Error>> {
    dotenv::dotenv().ok();

    tonic_prost_build::configure()
        .protoc_arg("--experimental_allow_proto3_optional")
        .build_server(true)
        // .out_dir("src/generated")
        .compile_protos(&["proto/encoderfile.proto"], &["proto/encoderfile"])?;

    for var in BUILD_VARS {
        let val = std::env::var(var).expect("Missing required environment variable: {var}");

        println!("cargo:rustc-env={var}={val}");
    }

    // generated file
    let out_dir = std::env::var("OUT_DIR").unwrap();

    // let out_dir = std::path::Path::new(out_dir.as_str());
    // let dir = out_dir.join("generated/transform");
    // std::fs::create_dir_all(&dir).unwrap();

    let write_dir = std::path::Path::new(&out_dir).join("generated/transform.rs");

    if let Ok(transform_path) = std::env::var("TRANSFORM_PATH") {
        println!("cargo:rustc-env=TRANSFORM_PATH={transform_path}");

        std::fs::write(write_dir, TRANSFORM_FILE).unwrap();
    } else {
        std::fs::write(write_dir, TRANSFORM_FILE_NONE).unwrap();
    }

    Ok(())
}
