# generated by datamodel-codegen:
#   filename:  build_config.schema.json
#   timestamp: 2025-10-31T16:44:05+00:00

from __future__ import annotations

from enum import Enum
from typing import Optional

from pydantic import BaseModel


class ModelType(Enum):
    embedding = 'embedding'
    sequence_classification = 'sequence_classification'
    token_classification = 'token_classification'


class ModelConfig(BaseModel):
    model_config_path: Optional[str] = None
    model_weights_path: Optional[str] = None
    name: str
    path: Optional[str] = None
    tokenizer_path: Optional[str] = None
    type: ModelType


class BuildConfig(BaseModel):
    model: ModelConfig
