---Generated by Encoderfile ❤️
---Remember: Lua is 1-indexed!

MatryoshkaDim = 512
Eps = 1e-5

---Postprocessing script follows instructions from the official model repository:
---https://huggingface.co/nomic-ai/nomic-embed-text-v1.5

---Postprocess embeddings
---Must return 2D tensor of shape [batch_size, *]
---@input Tensor 3D tensor of shape [batch_size, seq_len, hidden_dim]
---@input mask Attention mask of shape [batch_size, seq_len]
---@return Tensor
function Postprocess(arr, mask)
    ---Step 1: mean pool
    local embeddings = arr:mean_pool(mask)

    ---Step 2: layer_norm along 2nd axis (1st axis in PyTorch land)
    embeddings = embeddings:layer_norm(2, Eps)

    ---Step 3: truncate along 2nd axis
    embeddings = embeddings:truncate_axis(2, MatryoshkaDim)

    ---Step 4: l2 normalize along 2nd axis
    embeddings = embeddings:lp_norm(2.0, 2)

    return embeddings
end
