---Generated by Encoderfile ❤️
---Remember: Lua is 1-indexed!

---Postprocess embeddings
---Must return 3D tensor of shape [batch_size, seq_len, *]
---@input Tensor 3D tensor of shape [batch_size, seq_len, hidden_dim]
---@return Tensor
function Postprocess(arr)
    ---Replace with your logic here
    return arr
end
