---Generated by Encoderfile ❤️
---Remember: Lua is 1-indexed!

---Postprocess sequence classification logits
---Must return 2D tensor of shape [batch_size, n_labels]
---@input Tensor 2D tensor of shape [batch_size, n_labels]
---@return Tensor
function Postprocess(arr)
    ---Replace with your logic here
    return arr
end
