---Generated by Encoderfile ❤️
---Remember: Lua is 1-indexed!

---Postprocess sequence classification logits
---Must return 3D tensor of shape [batch_size, seq_len, n_labels]
---@input Tensor 3D tensor of shape [batch_size, seq_len, n_labels]
---@return Tensor
function Postprocess(arr)
    ---Replace with your logic here
    return arr
end
