name: "Project Setup"
description: "Shared environment setup for CI"
inputs:
  toolchain:
    description: "Rust toolchain to install"
    required: false
    default: "stable"

runs:
  using: "composite"
  steps:
    - uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: ${{ inputs.toolchain }}

    - uses: actions/setup-python@v5
      with:
        python-version: "3.13"

    - name: Install system dependencies
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y protobuf-compiler libssl-dev pkg-config cmake zlib1g-dev libdw-dev binutils-dev libelf-dev

    - name: Install uv
      shell: bash
      run: curl -LsSf https://astral.sh/uv/install.sh | sh

    - name: Project setup
      shell: bash
      run: make setup
    
    - name: Install cargo-binstall
      shell: bash
      run: |
        curl -L https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash
