name: "Project Setup"
description: "Shared environment setup for CI"
runs:
  using: "composite"
  steps:
    - uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: nightly

    - uses: actions/setup-python@v5
      with:
        python-version: "3.13"

    - name: Install system dependencies
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y protobuf-compiler libssl-dev pkg-config cmake zlib1g-dev libdw-dev binutils-dev libelf-dev

    - name: Install uv
      shell: bash
      run: curl -LsSf https://astral.sh/uv/install.sh | sh

    - name: Project setup
      shell: bash
      run: make setup

    - name: Generate dummy env file
      shell: bash
      run: uv run -m encoderbuild.utils.create_dummy_env_file > .env
